-- family_expense schema with merged admin table
CREATE DATABASE IF NOT EXISTS family_expense DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE family_expense;

CREATE TABLE admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  family_name VARCHAR(150) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  full_name VARCHAR(200),
  email VARCHAR(200),
  password_hash VARCHAR(255) NOT NULL,
  currency CHAR(3) DEFAULT 'INR',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member (
  id INT AUTO_INCREMENT PRIMARY KEY,
  admin_id INT NOT NULL,
  username VARCHAR(100) NOT NULL,
  full_name VARCHAR(200),
  email VARCHAR(200),
  allocated_budget DECIMAL(10,2) DEFAULT 0.00,
  spent_amount DECIMAL(10,2) DEFAULT 0.00,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE
);

CREATE TABLE expense (
  id INT AUTO_INCREMENT PRIMARY KEY,
  admin_id INT NOT NULL,
  member_id INT NULL,
  amount DECIMAL(10,2) NOT NULL,
  description VARCHAR(255),
  transaction_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE,
  FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE SET NULL
);

-- sample admin (username: head, password: password123)
INSERT INTO admin (family_name, username, full_name, email, password_hash) VALUES
('Arya Family', 'head', 'Yash Arya','yash@example.com', CONCAT('$2y$10$', REPEAT('a',53)) );
-- NOTE: replace the above hash with a real password_hash generated by PHP's password_hash before production.
